name: di
version: 3.0.0
authors:
- Vojta Jina <vojta.jina@gmail.com>
- Pavel Jbanov <pavelgj@gmail.com>
- Anting Shen <shenantingtt@gmail.com>
- Misko Hevery <misko@hevery.com>
- Victor Berchet <victor@suumit.com>
description: Dependency Injection framework
homepage: https://github.com/angular/di.dart
environment:
  sdk: '>=1.7.0-dev'
dependencies:
  analyzer: '>=0.15.0 <0.22.0'
  barback: '>=0.13.0 <0.16.0'
  code_transformers: '>=0.1.4 <0.3.0'
  path: ">=1.2.0 <2.0.0"
dev_dependencies:
  benchmark_harness: ">=1.0.4 <2.0.0"
  browser: ">=0.10.0 <0.11.0"
  guinness: ">=0.1.10 <0.2.0"
transformers:
- di/module_transformer
